# creates artifact of the packaged tarball
name: CD
on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn pack
      - uses: actions/upload-artifact@v1
        with:
          name: typescript-to-proptypess
          path: package.tgz
